config/routes.rb
Rails.application.routes.draw do
  get 'loans/index'
  get 'welcome/index'

  root 'welcome#index'

  resources :loans
  resources :friends
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :friender, class_name: "User"
  belongs_to :friended, class_name: "User"
end

app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :user  
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  has_many :active_friendships, class_name:  "Friendship",
                                  foreign_key: "friender_id",
                                  dependent:   :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :require_login

  def index
  end

  def new
    @loan = Loan.new
  end

  def create
    @loan = Loan.new(loan_params)
    # abort loan_params
    @loan.user = current_user
    if @loan.save
      redirect_to @loan
    else
      render 'new'
    end
  end

  def show
    @loan = Loan.find(params[:id])
  end

  private

    def loan_params
      params.require(:loan).permit(:card, :person)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>MTG Ledger</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <meta name="viewport" content="width=device-width, initial-scale=1">

      <%= stylesheet_pack_tag "application" %>
      <%= javascript_pack_tag "application" %>

      <link rel='stylesheet prefetch' href='https://use.fontawesome.com/releases/v5.0.10/css/all.css'>
    </head>
    <body>
      <nav class="navbar is-info">
        <div class="navbar-brand">
          <a class="navbar-item" href="#">
            <img src="https://bulma.io/images/bulma-logo.png" alt="Bulma: a modern CSS framework based on Flexbox" width="112" height="28">
          </a>
          <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
            <span></span>
            <span></span>
            <span></span>
          </div>
        </div>
        <div id="navbarExampleTransparentExample" class="navbar-menu">
          <div class="navbar-start is-link">
            <a class="navbar-item" href="/">
              Home
            </a>
            <div class="navbar-item has-dropdown is-hoverable">
              <a class="navbar-link" href="#">
                  My Account
              </a>
              <div class="navbar-dropdown is-boxed">
                <a class="navbar-item" href="#">
                    Trades
                </a>
                <a class="navbar-item" href="#">
                    Friends
                </a>
              </div>
            </div>
          </div>
          <div class="navbar-end">
            <% if signed_in? %>
            <div class="navbar-item">
              <p class="control">
                Signed in as: <%= current_user.email %>
                <%= button_to "Sign out", sign_out_path, method: :delete %>
              </p>
            </div>
            <% else %>
            <div class="navbar-item">
              <p class="control">
                <span class="icon">
                  <i class="fas fa-user-plus"></i>
                </span>
                <%= link_to 'Sign in', sign_in_path %>
              </p>
            </div>
            <div class="navbar-item">
              <p class="control">
                <span class="icon">
                  <i class="fas fa-user-plus"></i>
                </span>
                <%= link_to sign_up_path do %>
                  <span>Sign Up</span>
                <% end %>
              </p>
            </div>
            <% end %>
          </div>
        </div>
      </nav>
      <div id="flash">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
      </div>
      <section class="hero is-info">
        <div class="hero-body">
          <div class="container">
            <h1 class="title">
              MTG Ledger
            </h1>
            <h2 class="subtitle">
              Track which cards you've borrowed or loaned.
            </h2>
          </div>
        </div>
        <div class="tabs is-boxed is-centered main-menu" id="nav">
          <ul>
            <li class="<%= current_page?(loans_path) ? 'is-active' : '' %>">
              <a href="<%= loans_path %>">
                <span class="icon is-small"><i class="fa fa-book"></i></span>
                <span>Loans</span>
              </a>
            </li>
            <li class="<%= current_page?(friends_path) ? 'is-active' : '' %>">
              <a href="<%= friends_path %>">
                <span class="icon is-small"><i class="fa fa-user"></i></span>
                <span>Friends</span>
              </a>
            </li>
          </ul>
        </div>
      </section>
      <section>
        <div class="container">
          <%= yield %>
        </div>
      </section>
  </body>
</html>

app/views/loans/index.html.erb
<h1>Your Loans</h1>

<h2>
  <%= link_to 'Enter new loan', new_loan_path %>
</h2>

<p>
  You have no Loans...yet (:
</p>

app/views/loans/new.html.erb
<h1>Add Loan</h1>

<%= form_for(@loan) do |f| %>
  <%= f.label :card %>
  <%= f.text_field :card %>

  <%= f.label :person %>
  <%= f.text_field :person %>

  <%= f.submit "Save this loan", class: "btn btn-primary" %>
<% end %>

app/views/loans/show.html.erb
<h1>Show Loan</h1>

<p>
  You loaned card
  <span class="mtg-card">
    <%= @loan.card %>
  </span>
  to
  <span class="person">
    <%= @loan.person %>
  </span>

  on
  <span class="when">
    TODO: add timestamps
  </span>
</p>

app/views/welcome/index.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">
      MTG Ledger
    </h1>
    <p class="subtitle">
      Welcome to MTG Ledger! This app lets you easily track which cards you have loaned to your friends.
    </p>
    <p>
      When you're deck-building, you don't always want to buy a card just to try it out. Your friends may be willing to
      loan you cards you want that they're not using.
    </p>

    <p>
      But of course your friend will want their cards back. And being the good friend you are, you want to make sure
      you give them back too. MTG Ledger keeps track of every card loaned to or from your friends, so you never have
      to worry about keeping track of who each card belongs to.
    </p>
  </div>
</section>